#!/bin/sh
exec 2>&1


source /etc/profile
source /opt/rb/etc/sysconfig/rb-scanner-request

[ ! -f /opt/rb/etc/rb-uuid ] && cat /proc/sys/kernel/random/uuid > /opt/rb/etc/rb-uuid
HASH="$(cat /opt/rb/etc/rb-uuid)"

mkdir -p /opt/rb/etc/chef
mkdir -p /var/log/rb-scanner-request
cd /var/log/rb-scanner-request

echo "rB service started on $(hostname -f)"
exec /opt/rb/bin/rb_scanner_request -url "$URL" -hash "$HASH" -log finish.log -daemon false

sleep 60
